server:
  port: 8085
spring:
  cloud:
    gateway:
      routes:
        - id: user-management-service
          uri: http://localhost:8081/
          predicates:
            - Path=/api/user-management-service/**
        - id: showtime-service
          uri: http://localhost:8082/
          predicates:
            - Path=/api/showtime-service/**
